# Placement that selects all clusters from the global set
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: sveltos-ocm
  namespace: open-cluster-management-addon
spec:
  clusterSets:
    - global
