apiVersion: sveltos.open-cluster-management.io/v1alpha1
kind: SveltosOCMCluster
metadata:
  labels:
    app.kubernetes.io/name: sveltos-ocm-addon
    app.kubernetes.io/managed-by: kustomize
  name: sveltosocmcluster-sample
spec:
  # Namespace where SveltosCluster resources will be created
  # Default: sveltos
  sveltosNamespace: sveltos

  # Token validity period (golang duration string)
  # Default: 168h (7 days)
  tokenValidity: "168h"

  # Sync labels from ManagedCluster to SveltosCluster
  # Default: true
  labelSync: true
